# Generated by Django 3.1.6 on 2021-08-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(verbose_name='creation date')),
                ('telephone_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('dateofjoining', models.DateField(auto_now_add=True, verbose_name='dateofjoining')),
                ('field', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Programmer'), ('D', 'Digial Marketing'), ('A', 'Architectural'), ('O', 'Other')], default=0, max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('field', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Programmer'), ('D', 'Digial Marketing'), ('A', 'Architectural'), ('O', 'Other')], default=0, max_length=7)),
                ('dateofjoining', models.DateField(auto_now_add=True, verbose_name='dateofjoining')),
                ('resume', models.ImageField(null=True, upload_to='Image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Image/')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('expire_date', models.DateField()),
                ('field', models.CharField(choices=[('P', 'Programmer'), ('D', 'Digial Marketing'), ('A', 'Architectural'), ('O', 'Other')], max_length=1)),
                ('salary', models.IntegerField(default=0)),
                ('working_hours', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.job')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
            ],
        ),
    ]
